title: Cyber Oasis
baseurl: /cyber-oasis

exclude: ["Gemfile", "Gemfile.lock", "node_modules", "vendor/bundle/", "vendor/cache/", "vendor/gems/", "vendor/ruby/", "readme.md", ".gitignore"]

sass:
    sass_dir: assets/sass

collections_dir: collections
collections:
    food:
        output: true
    thoughts:
        output: true
